name: Claude Code

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  claude:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'issues' && (contains(github.event.issue.body, '@claude') || contains(github.event.issue.title, '@claude')))
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      issues: read
      id-token: write
      actions: read # Required for Claude to read CI results on PRs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude Code
        id: claude
        uses: anthropics/claude-code-action@v1
        env:
          ANTHROPIC_BASE_URL: https://api.z.ai/api/anthropic
        with:
          anthropic_api_key: ${{ secrets.ZAI_API_KEY }}

          additional_permissions: |
            actions: read

          # This prompt tells Claude what to do when working on an issue
          prompt: |
            When asked to work on an issue, please:
            1. Create a new branch from the default branch, naming it according to the issue (e.g., issue-${{ github.event.issue.number }}-short-description).
            2. Make the required changes/fixes as described in the issue.
            3. Open a pull request from the new branch to the default branch, referencing the issue in the PR description.
            4. Add a summary of changes in the PR description.

          claude_args: "--model glm-4.6"
