name: Test and Verify

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test-and-verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      # Build (replaces deprecated 'go get .')
      - name: Build
        run: go build ./...

      - name: Run tests
        run: go test -v ./...

      - name: Vet code
        run: go vet ./...

      - name: Install vhs
        run: go install github.com/charmbracelet/vhs@latest

      - name: Verify Tapes
        run: |
          export PATH=$(go env GOPATH)/bin:$PATH
          vhs .tapes/*.tape