name: Test and Verify

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Build
        run: go build ./...

      - name: Run unit tests
        env:
          CLICOLOR_FORCE: 1
          FORCE_COLOR: 1
          COLORTERM: truecolor
        run: go test -v -short ./...

      - name: Vet code
        run: go vet ./...

  integration-tests:
    name: VHS Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Install VHS
        run: |
          wget https://github.com/charmbracelet/vhs/releases/download/v0.7.2/vhs_0.7.2_amd64.deb
          sudo dpkg -i vhs_0.7.2_amd64.deb
          sudo apt-get install -f -y

      - name: Install ffmpeg (VHS dependency)
        run: sudo apt-get install -y ffmpeg

      - name: Run VHS integration tests
        env:
          CLICOLOR_FORCE: 1
          FORCE_COLOR: 1
          COLORTERM: truecolor
          TERM: xterm-256color
        run: go test -v -run TestVHS ./...

      - name: Upload demo GIFs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: vhs-demos
          path: .tapes/assets/*.gif
          if-no-files-found: ignore

